### Get Orders
GET http://localhost:4004/odata/v4/manage-orders/GetOrders

### Get Order
GET http://localhost:4004/odata/v4/manage-orders/GetOrders('client1@client1.com')

### Create Order
POST http://localhost:4004/odata/v4/manage-orders/CreateOrder HTTP/1.1
Content-Type: application/json

{
    "ClientEmail"   : "client5@client5.com",
    "FirstName"     : "Nataly",
    "LastName"      : "Ortegon",
    "CreatedOn"     : "2024-10-10"
}

### Update Order
PUT http://localhost:4004/odata/v4/manage-orders/UpdateOrder('client1@client1.com') HTTP/1.1
Content-Type: application/json

{
    "FirstName" : "FirstName Updated",
    "LastName"  : "LastName Updated"
}